### PR TITLE
Blog: Announcing polygigs

### PR DESCRIPTION
**Pull request by zacharytamas**
Believe the post is mostly done but working on layout.

### CODE REVIEW

**Comment by adamduren** [comment]
image

Maybe we should move the author name by the date with a separator like an M-dash.?

**Comment by adamduren** [comment]
Good overall. How about a related image at the start or somewhere along the post?

**Comment by adamduren** [comment]
Maybe we should either provide a TLDR or link to Polygigs sooner.

**Comment by zacharytamas** [comment]
Oh yeah the template was not finalized by any means. We should put the byline somewhere more sensible, I was just confirming that I was fetching the right user.

**Comment by zacharytamas** [comment]
I think this is mergeable though I'm about to do more work on it such as iterative design work.

**Pull request merged**
